# Dockerfile.frontend

FROM node:22-alpine

# Declare build-time argument
ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

WORKDIR /app

COPY ./package*.json ./
RUN npm install

COPY . ./

# This is where Next.js reads env vars for client-side use
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
